import React from 'react'

export default function SecurityComp() {
    return (
        <div>
            <h4 style={{ color: "#8D4000" }}>Security</h4>
            <p style={{ color: "#1A374D" }}>
                You can reach us via our phone numbers, social media profiles, email etc.
            </p>

            <div className='mt-5'>
                <div className="row">
                    <div className="col-md-10">
                        <p className='mb-2'>Authenticator app code</p>
                        <p className='text-secondary mb-0'>Enter a code generated by your authenticator app to confirm it’s you.</p>
                    </div>
                    <div className="col-md-2">
                        <label className="switch">
                            <input
                                type="checkbox"
                            />
                            <span className="slider" />
                        </label>
                    </div>
                </div><hr />

                <div className="row">
                    <div className="col-md-10">
                        <p className='mb-2'>Text Message</p>
                        <p className='text-secondary mb-0'>Receive a six digit code by text message to confirm it’s you.</p>
                    </div>
                    <div className="col-md-2">
                        <label className="switch">
                            <input
                                type="checkbox"
                            />
                            <span className="slider" />
                        </label>
                    </div>
                </div><hr />
            </div>
        </div>
    )
}
